### ISSUE TITLE
Не запускаться jar-файл, приложение не разворачивается на localhost:8080

### ISSUE THREAD

**Issue by MrLaikaBoss** [MrLaikaBoss/QA-diploma#1]
### Предусловия:
Запускаю как всегда, но jar-файл не запускается. Я несколько раз переписывал файл, может быть что-то где-то удалил или изменил нужное, или проблема с портами. Самостоятельно найти ответ в интернете не получилось.
Файлы: docker-compose.yml, application.properties, DockerFile созданы.

#### Шаги воспроизведения

1. Запустить Docker Container в IntelliJIDEA через терминал 1 командой `docker-compose up -d`.
2. Запустить в IntelliJIDEA через терминал 2 jar-файл командой `java -jar ./artifacts/aqa-shop.jar`

_**Ожидаемый результат**:_ приложение развернуто на `localhost:8080` .

_**Фактический результат**:_ приложение не разворачивается, jar-файл не запускается.

#### Скриншоты:

1. ![Скриншот-23-10-2023 19_01_31](https://github.com/MrLaikaBoss/QA-diploma/assets/131680949/fd889bfd-ed14-4b97-a785-5d7bd6a9c768)
2. ![Скриншот-23-10-2023 19_00_20](https://github.com/MrLaikaBoss/QA-diploma/assets/131680949/52b149d1-3ada-4479-bba7-1456a23401ad)
3. ![Скриншот-23-10-2023 19_03_12](https://github.com/MrLaikaBoss/QA-diploma/assets/131680949/b4542213-30a7-4bdf-9da9-3f67473e2544)
4. ![Скриншот-23-10-2023 19_02_47](https://github.com/MrLaikaBoss/QA-diploma/assets/131680949/fb50a2a0-f684-4320-b2de-7959a23f9252)

#### Окружение:
Windows 10 Pro
Docker Engine v24.0.5
IntelliJ IDEA 2023.1.1 (Community Edition)
Google Ghrome Версия 118.0.5993.89 (Официальная сборка), (64 бит)

**Comment by ArRomanov** [comment]
У вас имя пользователя для mysql задано как user - https://github.com/MrLaikaBoss/QA-diploma/blob/main/docker-compose.yml#L10
А в application.properties вы используете app - https://github.com/MrLaikaBoss/QA-diploma/blob/main/application.properties#L4
